- name: Install AWX Operator
  hosts: k8s_master
  become: true

  tasks:
    - name: Create awx namespace
      command: kubectl create namespace awx
      ignore_errors: true

    - name: Install operator
      command: >
        kubectl apply -k
        github.com/ansible/awx-operator/config/default?ref=release-2.12.0
